obj-$(CONFIG_USE_OF) += board-dt.o
obj-$(CONFIG_ARCH_MDM9640) += board-9640.o
obj-$(CONFIG_ARCH_MDM9607) += board-9607.o
obj-$(CONFIG_ARCH_MDM9650) += board-9650.o
obj-$(CONFIG_ARCH_SDX20) += board-sdx20.o
obj-$(CONFIG_ARCH_MSM8916) += board-8952.o
obj-$(CONFIG_ARCH_MSM8917) += board-8917.o
obj-$(CONFIG_ARCH_MSM8920) += board-8920.o
obj-$(CONFIG_ARCH_MSM8937) += board-8937.o
obj-$(CONFIG_ARCH_MSMTITANIUM) += board-titanium.o
obj-$(CONFIG_ARCH_MSM8909) += board-8909.o board-8909-gpiomcu.o

#SMP
obj-$(CONFIG_SMP) += headsmp.o platsmp.o
obj-$(CONFIG_HOTPLUG_CPU) += hotplug.o
